// <auto-generated />
using System;
using BarnManagement.DataAccess.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarnManagement.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BarnManagement.Core.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("char(36)");

                    b.Property<int>("LifeSpanDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("NextProductionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductionInterval")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Animals__3214EC0714C678DB");

                    b.HasIndex(new[] { "FarmId" }, "IX_Animals_FarmId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("BarnManagement.Core.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id")
                        .HasName("PK__Farms__3214EC0764F68B70");

                    b.HasIndex("OwnerId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("BarnManagement.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ProducedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Products__3214EC0786C019E2");

                    b.HasIndex(new[] { "FarmId" }, "IX_Products_FarmId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BarnManagement.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0789DD88B2");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053481A44601")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BarnManagement.Core.Entities.Animal", b =>
                {
                    b.HasOne("BarnManagement.Core.Entities.Farm", "Farm")
                        .WithMany("Animals")
                        .HasForeignKey("FarmId")
                        .IsRequired()
                        .HasConstraintName("FK_Animals_Farms");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("BarnManagement.Core.Entities.Farm", b =>
                {
                    b.HasOne("BarnManagement.Core.Entities.User", "Owner")
                        .WithMany("Farms")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Farms_Users");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BarnManagement.Core.Entities.Product", b =>
                {
                    b.HasOne("BarnManagement.Core.Entities.Farm", "Farm")
                        .WithMany("Products")
                        .HasForeignKey("FarmId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Farms");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("BarnManagement.Core.Entities.Farm", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("BarnManagement.Core.Entities.User", b =>
                {
                    b.Navigation("Farms");
                });
#pragma warning restore 612, 618
        }
    }
}
