@host = http://localhost:5193

### Register User
# @name register
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "testfarm@example.com",
  "username": "farmowner",
  "password": "Password123!"
}

### Login User
# @name login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "testfarm@example.com",
  "password": "Password123!"
}

### Get Token
@authToken = {{login.response.body.token}}

### Get User Profile
GET {{host}}/api/users/me
Authorization: Bearer {{authToken}}

### Create Farm
# @name createFarm
POST {{host}}/api/farms
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "My First Farm"
}

### Get User Farms
GET {{host}}/api/farms
Authorization: Bearer {{authToken}}

### Get Farm By Id
@farmId = {{createFarm.response.body.id}}
GET {{host}}/api/farms/{{farmId}}
Authorization: Bearer {{authToken}}

### Update Farm
PUT {{host}}/api/farms/{{farmId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Updated Farm Name"
}

### Delete Farm
DELETE {{host}}/api/farms/{{farmId}}
Authorization: Bearer {{authToken}}
